[package]
name = "world_gen"
version = "0.1.0"
authors = ["nr6000000 <kgrybek1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.0"
noise = "0.6.0"
libmath = "0.2.1"
rand = "0.7.2"
